trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - .gitignore
      - README.md
      - AdHocs/*

pr: none

pool:
  vmImage: 'windows-2019'

variables:
  - group: ServiceBus.IntegrationTests

name: 4.0$(Rev:.r)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore from Nuget.org and EmmersionLearning feeds'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'

- task: FileTransform@1
  displayName: 'Integration test file transform'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/Emmersion.ServiceBus.IntegrationTests'
    fileType: json
    targetFiles: appsettings.json

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    packagesToPack: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/Emmersion.ServiceBus.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: 'Publish'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'